### ISSUE TITLE
Uncaught TypeError: locale() locale es is not loaded from moment locales!

### ISSUE THREAD

**Issue by yceruto** [symfony/symfony-demo#591]
Just after installed all current deps and build the missing assets files, I received this error in the browser console when I accessing to `admin/post/1/edit`:
```
[common.js:3865]
jQuery.Deferred exception: locale() locale es is not loaded from moment locales! TypeError: locale() locale es is not loaded from moment locales!
    at Object.picker.locale (http://symfony-demo.com/build/js/admin.js:4312:23)
    at String.<anonymous> (http://symfony-demo.com/build/js/admin.js:4005:32)
    at Function.each (http://symfony-demo.com/build/js/common.js:373:19)
    at Object.picker.options (http://symfony-demo.com/build/js/admin.js:4003:15)
    at dateTimePicker (http://symfony-demo.com/build/js/admin.js:4867:16)
    at HTMLDivElement.<anonymous> (http://symfony-demo.com/build/js/admin.js:4929:50)
    at Function.each (http://symfony-demo.com/build/js/common.js:367:19)
    at jQuery.fn.init.each (http://symfony-demo.com/build/js/common.js:162:17)
    at jQuery.fn.init.$.fn.datetimepicker (http://symfony-demo.com/build/js/admin.js:4923:25)
    at HTMLDocument.<anonymous> (http://symfony-demo.com/build/js/admin.js:7628:41) undefined
jQuery.Deferred.exceptionHook @ common.js:3865
process @ common.js:3660

[common.js:3874]
Uncaught TypeError: locale() locale es is not loaded from moment locales!
    at Object.picker.locale (admin.js:4312)
    at String.<anonymous> (admin.js:4005)
    at Function.each (common.js:373)
    at Object.picker.options (admin.js:4003)
    at dateTimePicker (admin.js:4867)
    at HTMLDivElement.<anonymous> (admin.js:4929)
    at Function.each (common.js:367)
    at jQuery.fn.init.each (common.js:162)
    at jQuery.fn.init.$.fn.datetimepicker (admin.js:4923)
    at HTMLDocument.<anonymous> (admin.js:7628)
picker.locale @ admin.js:4312
(anonymous) @ admin.js:4005
each @ common.js:373
picker.options @ admin.js:4003
dateTimePicker @ admin.js:4867
(anonymous) @ admin.js:4929
each @ common.js:367
each @ common.js:162
$.fn.datetimepicker @ admin.js:4923
(anonymous) @ admin.js:7628
mightThrow @ common.js:3588
process @ common.js:3656
```
so the datetimepicker and tagsinput doesn't work! :(

I've also noticed one diff in my `yarn.lock` file after installing the dependencies, it seems to be an order issue:
```diff
diff --git a/yarn.lock b/yarn.lock
index 26fca22..5ecc7cf 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -3680,15 +3680,15 @@ right-align@^0.1.1:
   dependencies:
     align-text "^0.1.1"
 
-rimraf@2, rimraf@^2.5.1, rimraf@^2.6.1:
-  version "2.6.1"
-  resolved "https://registry.yarnpkg.com/rimraf/-/rimraf-2.6.1.tgz#c2338ec643df7a1b7fe5c54fa86f57428a55f33d"
+rimraf@2, rimraf@~2.5.1:
+  version "2.5.4"
+  resolved "https://registry.yarnpkg.com/rimraf/-/rimraf-2.5.4.tgz#96800093cbf1a0c86bd95b4625467535c29dfa04"
   dependencies:
     glob "^7.0.5"
 
-rimraf@~2.5.1:
-  version "2.5.4"
-  resolved "https://registry.yarnpkg.com/rimraf/-/rimraf-2.5.4.tgz#96800093cbf1a0c86bd95b4625467535c29dfa04"
+rimraf@^2.5.1, rimraf@^2.6.1:
+  version "2.6.1"
+  resolved "https://registry.yarnpkg.com/rimraf/-/rimraf-2.6.1.tgz#c2338ec643df7a1b7fe5c54fa86f57428a55f33d"
   dependencies:
     glob "^7.0.5"
```
I don't know, maybe I'm doing something wrong?

`yarn --version` = 0.24.6

**Comment by stof** [comment]
I suspect that the lock file was generated with the unstable version of Yarn (0.26). @javiereguiluz can you tell us which version of Yarn you use ?
Otherwise, it is a bug in Yarn itself which should be reported.

@alOneh looks like we were too quick at dropping moment locales from the bundle file. It looks like we actually need the locales.

**Comment by yceruto** [comment]
Ah, I forgot to say that the error only happen for locales different to "English" which works fine!

**Comment by alOneh** [comment]
@yceruto I'm not able to reproduce this error.
Can you try to load explicitly the locale `es` ?

**Comment by yceruto** [comment]
I tried commenting this line:
```js
//config.plugins.push(new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/));
```
and all works fine again, reading this line... shouldn't be ignoring all locales here?

**Comment by yceruto** [comment]
> @alOneh Can you try to load explicitly the locale es ?

Sorry I'm not sure what do you mean exactly?
